#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/lib/games"

cleanup() {
    echo "CLEAN"
}

trap cleanup EXIT

sudo -v

game=$(resolve_game "$1")

root="$PWD/games/$game"

mods_dir="$root/mods"
upper_dir="$root/merged"
work_dir="$root/work"
run_dir="$root/run"

case "$game" in
    "Cyberpunk 2077")
        install_dir="$HOME/.steam/steam/steamapps/common/Cyberpunk 2077"
        compatdata_dir="$HOME/.steam/steam/steamapps/compatdata/1091500"
        game_executable="$run_dir/bin/x64/Cyberpunk2077.exe"
        ;;
    "Skyrim Special Edition")
        install_dir="$HOME/.steam/steam/steamapps/common/Skyrim Special Edition"
        compatdata_dir="$HOME/.steam/steam/steamapps/compatdata/489830"
        game_executable="$run_dir/skse64_loader.exe"
        ;;
esac

sudo umount "$run_dir" &>/dev/null # Just in case
sudo rm -rf "$work_dir" "$run_dir"
mkdir -p "$work_dir" "$run_dir"

mkdir -p "$upper_dir" "$mods_dir" # TEMPORARY, will be removed when copying mods.

sudo mount -t overlay overlay \
    -o "lowerdir=$install_dir,upperdir=$upper_dir,workdir=$work_dir" \
    "$run_dir"

STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam" \
    STEAM_COMPAT_DATA_PATH="$compatdata_dir" \
    WINEDLLOVERRIDES="winmm,version=n,b" \
    "$HOME/.steam/steam/steamapps/common/Proton - Experimental/proton" \
    waitforexitandrun "$game_executable"
