#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/lib/games"

usage() {
    echo "Usage: launch-game <game-name>"
}

cleanup() {
    if ! mountpoint -q "$run_dir"; then
        return
    fi

    if sudo umount "$run_dir"; then
        return
    fi

    echo "Failed to unmount: $run_dir" >&2

    return 1
}

wait_for_mount_users() {
    # Wait until process appears.
    for _ in {1..10}; do
        if sudo fuser -m "$run_dir" >/dev/null 2>&1; then
            break
        fi

        sleep 1
    done

    # Actual wait loop until mount disappears.
    while sudo fuser -m "$run_dir" >/dev/null 2>&1; do
        sleep 1
    done
}

trap cleanup EXIT

if (($# != 1)); then
    usage >&2
    exit 1
fi

game=$(resolve_game "$1")

if [[ -z "$game" ]]; then
    echo "Unknown game: $1" >&2
    exit 1
fi

sudo -v

root="$PWD/games/$game"

mods_dir="$root/mods"
merged_dir="$root/merged"
upper_dir="$root/sink"
work_dir="$root/work"
run_dir="$root/run"

case "$game" in
    "Cyberpunk 2077")
        install_dir="$HOME/.steam/steam/steamapps/common/Cyberpunk 2077"
        compatdata_dir="$HOME/.steam/steam/steamapps/compatdata/1091500"
        game_executable="$run_dir/bin/x64/Cyberpunk2077.exe"
        ;;
    "Skyrim Special Edition")
        install_dir="$HOME/.steam/steam/steamapps/common/Skyrim Special Edition"
        compatdata_dir="$HOME/.steam/steam/steamapps/compatdata/489830"
        game_executable="$run_dir/skse64_loader.exe"
        ;;
esac

sudo rm -rf "$work_dir" "$run_dir"
mkdir -p "$work_dir" "$run_dir" "$upper_dir"

# In overlayfs lowerdir order, the leftmost lower layer is above later layers.
sudo mount -t overlay overlay \
    -o "lowerdir=$merged_dir:$install_dir,upperdir=$upper_dir,workdir=$work_dir" \
    "$run_dir" || exit 1

cd "$run_dir"

STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam" \
    STEAM_COMPAT_DATA_PATH="$compatdata_dir" \
    WINEDLLOVERRIDES="winmm,version=n,b" \
    "$HOME/.steam/steam/steamapps/common/Proton - Experimental/proton" \
    waitforexitandrun "$game_executable" >/dev/null 2>&1
proton_status=$?

cd "$SCRIPT_DIR"

wait_for_mount_users

exit "$proton_status"
