#!/usr/bin/env bash

resolve_game() {
    local game="${1,,}"

    case "$game" in
        "cyberpunk 2077" | cyberpunk | cyberpunk2077 | cbp)
            echo "Cyberpunk 2077"
            ;;
        "skyrim special edition" | skyrim | es5)
            echo "Skyrim Special Edition"
            ;;
        minecraft | mc)
            echo "Minecraft"
            ;;
    esac
}
